version: "3.7"
x-project-base:
  &project-base
  restart: always
  networks:
    - remixide

networks:
  remixide:

services:
  remixide:
    <<: *project-base
    image: remixproject/remix-ide:$TAG
    container_name: remixide-${TAG}
    hostname: remixide
    ports:
      - 8080:80
  remixd:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    <<: *project-base
    image: contractshark/workspace/remixd:latest
    container_name: remixd
    hostname: remixd
    ports:
      - 65520:65520
    volumes:
    - ./:/app
