name: hadolint

on:
  push:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: hadolint/hadolint-action@v2.1.0
      id: hadolint
      with:
       dockerfile: Dockerfile
